/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle;

import gradle.Scenes.MainScene;
import gradle.Scenes.SplashScreen;
import javafx.application.Application;
import javafx.application.Platform;
import javafx.scene.Scene;
import javafx.scene.image.Image;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

public class App extends Application {

    @Override
    public void start(Stage stage) throws Exception {
        stage.setResizable(false);
        Image imageIcon = new Image(getClass().getClassLoader().getResourceAsStream("Style/foto/logo.jpg"));
        stage.getIcons().add(imageIcon);

        SplashScreen splashScreen = new SplashScreen(stage);
        splashScreen.show();

        new Thread(() -> {
            try {
                Thread.sleep(2000);
            } catch (InterruptedException e) {
                e.printStackTrace();
            }

            Platform.runLater(() -> {
                stage.close();

                VBox root = new VBox();
                Scene scene = new Scene(root, 740, 580);
                stage.setScene(scene);
                stage.show();

                MainScene mainScene = new MainScene(stage);
                mainScene.show();
            });
        }).start();
    }

    public static void main(String[] args) {
        launch();
    }

}
